CREATE UNIQUE INDEX IF NOT EXISTS uq_metas_unidade_unidade_id_mes ON metas_unidade (unidade_id, mes);
CREATE UNIQUE INDEX IF NOT EXISTS uq_metas_colaborador_colaborador_id_unidade_id_mes ON metas_colaborador (colaborador_id, unidade_id, mes);
CREATE UNIQUE INDEX IF NOT EXISTS uq_estoque_produto_id_unidade_id ON estoque (produto_id, unidade_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carteira_pontos_cliente_id ON carteira_pontos (cliente_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_uso_plano_mes_assinatura_id_servico_id_ano_mes ON uso_plano_mes (assinatura_id, servico_id, ano_mes);
CREATE UNIQUE INDEX IF NOT EXISTS uq_permissoes_tela_perfil_tela ON permissoes_tela (perfil, tela);
CREATE UNIQUE INDEX IF NOT EXISTS uq_permissoes_funcao_perfil_funcao ON permissoes_funcao (perfil, funcao);
CREATE UNIQUE INDEX IF NOT EXISTS uq_push_lembretes_agendamento_id_tipo ON push_lembretes (agendamento_id, tipo);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agenda_appbarber_appbarber_id ON agenda_appbarber (appbarber_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_appbarber_depara_profissional_unidade_id_appbarber_id ON appbarber_depara_profissional (unidade_id, appbarber_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_appbarber_depara_servico_unidade_id_appbarber_id ON appbarber_depara_servico (unidade_id, appbarber_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_colaborador_servico_tempo_colaborador_id_servico_id ON colaborador_servico_tempo (colaborador_id, servico_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_horarios_unidade_unidade_id_dia_semana ON horarios_unidade (unidade_id, dia_semana);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feriados_data ON feriados (data);
CREATE UNIQUE INDEX IF NOT EXISTS uq_colaboradores_email ON colaboradores (email);
CREATE UNIQUE INDEX IF NOT EXISTS uq_push_inscricoes_endpoint ON push_inscricoes (endpoint);
CREATE UNIQUE INDEX IF NOT EXISTS uq_categorias_produto_nome ON categorias_produto (nome);
CREATE UNIQUE INDEX IF NOT EXISTS uq_produtos_barcode ON produtos (barcode) WHERE barcode IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_comandas_unidade_id_status_finalizada_em ON comandas (unidade_id, status, finalizada_em);
CREATE INDEX IF NOT EXISTS ix_comandas_colaborador_id ON comandas (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_comandas_cliente_id ON comandas (cliente_id);
CREATE INDEX IF NOT EXISTS ix_comandas_agendamento_id ON comandas (agendamento_id);
CREATE INDEX IF NOT EXISTS ix_itens_comanda_comanda_id ON itens_comanda (comanda_id);
CREATE INDEX IF NOT EXISTS ix_itens_comanda_colaborador_id ON itens_comanda (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_itens_comanda_produto_id ON itens_comanda (produto_id);
CREATE INDEX IF NOT EXISTS ix_agendamentos_unidade_id_data_hora_ini ON agendamentos (unidade_id, data_hora_ini);
CREATE INDEX IF NOT EXISTS ix_agendamentos_colaborador_id_data_hora_ini ON agendamentos (colaborador_id, data_hora_ini);
CREATE INDEX IF NOT EXISTS ix_agendamentos_cliente_id ON agendamentos (cliente_id);
CREATE INDEX IF NOT EXISTS ix_agendamentos_status ON agendamentos (status);
CREATE INDEX IF NOT EXISTS ix_agenda_appbarber_unidade_id_inicio ON agenda_appbarber (unidade_id, inicio);
CREATE INDEX IF NOT EXISTS ix_agenda_appbarber_colaborador_id ON agenda_appbarber (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_agenda_appbarber_cliente_id ON agenda_appbarber (cliente_id);
CREATE INDEX IF NOT EXISTS ix_agenda_appbarber_produtos_unidade_id_data ON agenda_appbarber_produtos (unidade_id, data);
CREATE INDEX IF NOT EXISTS ix_agenda_appbarber_produtos_colaborador_id ON agenda_appbarber_produtos (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_clientes_whatsapp ON clientes (whatsapp);
CREATE INDEX IF NOT EXISTS ix_clientes_user_id ON clientes (user_id);
CREATE INDEX IF NOT EXISTS ix_clientes_unidade_pref ON clientes (unidade_pref);
CREATE INDEX IF NOT EXISTS ix_clientes_appbarber_codigo ON clientes (appbarber_codigo);
CREATE INDEX IF NOT EXISTS ix_colaboradores_unidade_id ON colaboradores (unidade_id);
CREATE INDEX IF NOT EXISTS ix_colaboradores_user_id ON colaboradores (user_id);
CREATE INDEX IF NOT EXISTS ix_assinaturas_cliente_id_status ON assinaturas (cliente_id, status);
CREATE INDEX IF NOT EXISTS ix_assinaturas_vendedor_id ON assinaturas (vendedor_id);
CREATE INDEX IF NOT EXISTS ix_historico_pontos_cliente_id_criado_em ON historico_pontos (cliente_id, criado_em);
CREATE INDEX IF NOT EXISTS ix_whatsapp_mensagens_conversa_id_criado_em ON whatsapp_mensagens (conversa_id, criado_em);
CREATE INDEX IF NOT EXISTS ix_whatsapp_conversas_numero ON whatsapp_conversas (numero);
CREATE INDEX IF NOT EXISTS ix_movimentacoes_estoque_produto_id_unidade_id ON movimentacoes_estoque (produto_id, unidade_id);
CREATE INDEX IF NOT EXISTS ix_vales_colaborador_id_status ON vales (colaborador_id, status);
CREATE INDEX IF NOT EXISTS ix_vales_pix_colaborador_id_status ON vales_pix (colaborador_id, status);
CREATE INDEX IF NOT EXISTS ix_notificacoes_whatsapp_status ON notificacoes_whatsapp (status);
CREATE INDEX IF NOT EXISTS ix_fechamentos_colaborador_id_periodo_ini ON fechamentos (colaborador_id, periodo_ini);
CREATE INDEX IF NOT EXISTS ix_caixa_sessoes_unidade_id_status ON caixa_sessoes (unidade_id, status);
CREATE INDEX IF NOT EXISTS ix_dre_lancamentos_unidade_id_mes ON dre_lancamentos (unidade_id, mes);